name: animestar
description: A new Flutter application.

publish_to: 'none'

version: 3.7.0+31

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  #Firebase
  firebase_auth: ^0.18.1+2
  firebase_core: ^0.5.0+1
  cloud_firestore: ^0.14.1+3
  firebase_messaging: ^7.0.3
  firebase_in_app_messaging: ^0.2.0+3
  google_sign_in: ^4.4.6
  http: ^0.12.2
  #icons
  flat_icons_flutter: ^1.0.2
  flutter_feather_icons: ^1.0.3
  fluttericon: ^1.0.7
  flutter_brand_icons: ^1.1.0
  flutter_badged: ^1.0.2
  flutter_icons: ^1.1.0
  #Ads
  facebook_audience_network: ^0.7.1
  unity_ads_flutter: ^1.1.0
  #utils
  swipedetector: ^1.2.0
  google_fonts: ^1.0.0
  flutter_sticky_header: ^0.4.2
  cached_network_image: 2.2.0+1
  loading: ^1.0.2
  webview_flutter: ^1.0.3
  shared_preferences: ^0.5.7
  url_launcher: ^5.4.5
  theme_provider: ^0.4.0+1
  intl: ^0.16.1
  carousel_slider: ^2.3.1
  in_app_review: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true